# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: A Strange Interface
subtitle: Looking for the ledo deck on the ship of Theseus 
description:
author: Derrick Burns
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://strangeinterface.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: hacker
#
# Hexo Filter Cleanup
hfc_useref:
  enable: true
  concat: true
  exclude:

hfc_html:
  enable: true
  exclude: 

hfc_css:
  enable: true
  exclude:
    - '*.min.css'

hfc_js:
  enable: true
  mangle: true
  output:
  compress:
  exclude:
    - '*.min.js'

hfc_img:
  enable: true
  interlaced: true
  multipass: false
  optimizationLevel: 2
  pngquant: false
  progressive: false
  webp: true
  webpQuality: 75
  gifslice: true
  jpegtran: true
  jpegrecompress: false
  jpegrecompressQuality: 'medium'
  optipng: true
  svgo: true

hfc_favicons:
  enable: false

# Feed
feed:
  type: rss2
  path: rss.xml
  limit: 20
  hub:
  content: 'true'

# Sitemap
  sitemap:
    path: sitemap.xml

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: s3-cloudfront
  prefix: ''
  force_overwrite: true
  headers: {CacheControl: 'max-age=604800, public'}
